export * as Confetti from './confetti';
export * as Select from './select';
export { default as AnimatedOutlet } from './animated-outlet';
export { default as VideoBackground } from './video-background';
export { default as PlayerCard } from './player-card';
export { default as Standings } from './standings';
export { default as Brackets } from './brackets';
export { default as Image } from './image';
export { default as Historial } from './historial';
export { default as Pagination } from './pagination';
